<?
$PERM["statistic_na"]["2"]="D";
$PERM["statistic_na"]["3"]="D";
$PERM["statistic_na"]["4"]="D";
$PERM["statistic_na"]["7"]="X";
$PERM["statistic_na"]["6"]="D";
$PERM["statistic_na"]["5"]="D";
$PERM["about"]["G6"]="W";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["5"]="W";
$PERM["/"]["*"]="R";
?>